import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  async function handleOnSubmit(e){
    e.preventDefault();
    var formData={};
    Array.from(document.getElementById("f").elements).forEach(element => {
      if(!element.name)
       return;
      formData[element.name]=element.value;
    });
    fetch("/api/mail",{
      method: "POST",
      body: JSON.stringify(formData)
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Mailer !
        </h1>
        <div className={styles.grid}>
          <style jsx>
            {`
              label{
                display : block;
                margin-bottom : .2em;
              }

              .button{
                color: white;
                background-color : #dd33fa;
                padding : .8em 1em;
                border : 0;
                border-radius : .8em;
              }
              .button:hover {
                background-color: pink;
              }
            `}
          </style>
          <form id="f" method="post">
            <p>
              <label htmlFor='name'>Sender's Name</label>
              <input type="text" name="name" />
            </p>
            <p>
              <label htmlFor='email'>Target email</label>
              <input type="email" name="email" />
            </p>
            <p>
              <label htmlFor='message'>Message Here</label>
              <textarea name="message" />
            </p>
            <p>
              <input type="submit" className='button' onClick={handleOnSubmit}/>
            </p>
          </form>
        </div>
      </main>
    </div>
  )
}
